language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c "create database store_manager_tests;" -U postgres
script:
  - export APP_SETTINGS="development"
  - export SECRET="SECRET"
  - export  ENV="testing"
  - py.test --cov=app app/tests/v2

after_success:
   - coveralls