language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
- sudo -u postgres psql
script:
  - export APP_SETTINGS="development"
  - export SECRET="SECRET"
  - export DATABASE_URL="dbname=store_manager user=postgres password=nyambumo"
  - pytest --cov-report term-missing --cov=app

  - coveralls

  - pytest --cov=app

after_success:
   - "coveralls"